dist: xenial

language: python

matrix:
  include:
    - python: pypy3.5-7.0.0
    - python: pypy3.6-7.1.1
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --upgrade codecov
  - python -m pip install --force-reinstall -r requirements.txt
  - python -m pip install --force-reinstall -r requirements-tests.txt

script:
  - pytest
  - python -m doctest README.md

after_success:
  - python -m codecov -f coverage.xml -X gcov

deploy:
  provider: pypi
  on:
    tags: true
    python: 3.5
  user: __token__
  password:
    secure: EV2/fSQtR4EyZFEU8EKG5NOw2I2QqWYk1OjSieWzDzN+Zrt9F+jQnakryjEZNjpHRXQ5UEnCkLt9htQFscoIpH1BzCJ4w6DZO0sg3kZsmGwUlskI9JCqC2iFoAKH0d44GmyLpr+uinoEv++t713yL3eVE+qjgW5ft0Ost40UtmxHwHZsSl1Ov/Z8dfTAdaTrtCotbG0LWi4rR+jUjJsoLJmsZhEscSRtz7xVdP6AWROc1oPvRC5PubAdKA31sMVCFS/g1iXiziwbbdGlPIcXQbkeC4USRjIXVC42sXgmBV9TqllOuvHjVAecUtpbG4hGrM1wa3HQWmQTl/EcDlq2BhpUhrN8RWopT/HhI4l4d+MJwwYM4bf3pUnX7qzkZX9OFa6kyxaw+1Phyoe+DsOvwASg36hywzQfJYfwCVyULp5yFzcXudvI7gGEXLwry6cQEvEpo3ABviY/h3Ac1szNeSlce9x37r9LYsvW1ZgAfHluCBYwFgr9snLA+g0JqfFz4i3LRtRp7lOzX4B0zPT0kcdauilUpa6ys7rBUQWTjfpRZMTslvxayU1XW8X/2QpWyPl991YiuPuZrUg/o6Nrl6KU0KvPeBwa3GA4TssYbYOshgu4qqh2yoc70u/Gd4iSnmODRgpYTxJo2qoQNeUT7q7PyRBO+oNBQALD0+xFVb8=
  distributions: sdist bdist_wheel
  skip_existing: true
