version: '3'

services:
  decision-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/decision-cpython:0.3.0-alpha
    volumes:
      - ./decision:/opt/decision/decision
      - ./pytest.ini:/opt/decision/pytest.ini
      - ./README.md:/opt/decision/README.md
      - ./requirements-tests.txt:/opt/decision/requirements-tests.txt
      - ./requirements.txt:/opt/decision/requirements.txt
      - ./setup.py:/opt/decision/setup.py
      - ./tests:/opt/decision/tests
    entrypoint: pytest
