version: '3'

services:
  decision-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/decision-pypy:0.3.1
    volumes:
      - ./decision:/opt/decision/decision
      - ./pyproject.toml:/opt/decision/pyproject.toml
      - ./README.md:/opt/decision/README.md
      - ./setup.py:/opt/decision/setup.py
      - ./tests:/opt/decision/tests
    entrypoint: pytest
