version: '3'

services:
  decision-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/decision-cpython:0.4.0
    volumes:
      - ./decision:/opt/decision/decision
      - ./pyproject.toml:/opt/decision/pyproject.toml
      - ./README.md:/opt/decision/README.md
      - ./setup.py:/opt/decision/setup.py
      - ./tests:/opt/decision/tests
    entrypoint: pytest
